SCRIPTING_TECNAI = "Tecnai.Instrument"
SCRIPTING_STD = "TEMScripting.Instrument.1"
SCRIPTING_ADV = "TEMAdvancedScripting.AdvancedInstrument.2"
SCRIPTING_LOWDOSE = "LDServer.LdSrv"
SCRIPTING_TIA = "ESVision.Application"
SCRIPTING_SEM_CCD = "SerialEMCCD.DMCamera.1"
SCRIPTING_TECNAI_CCD = "TecnaiCCD.GatanCamera.2"
SCRIPTING_FEI_GATAN_REMOTING = "ThermoScientificTEMPlugin.GMSPlugin"
#SCRIPTING_FEI_GATAN_REMOTING = "ThermoScientificTEMPlugin.Acquisition.1"

LICENSE_ADV = "TEMAdvancedScripting.AdvancedInstrumentInternal"
LICENSE_ADV_CAM = "TEMAdvancedScripting.CameraSettingsInternal"
