# Workflow to send master to pypi and tag the branch
name: master to pypi with comments and tag

# Triggers the workflow on push to the master branch
on:
  push:
    branches: [ master ]

env:
  FOLDER_WITH_VERSION: pytemscript
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine build
        pip install numpy mrcfile
    - name: Check extra requirements
      if: ${{ hashFiles('requirements.txt') != '' }}
      run: pip install -r requirements.txt
    - name: publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build --no-isolation
        twine upload dist/*
    - name: Get version and tag
      run: |
        export PACKAGE_VERSION=$(python -c "import $FOLDER_WITH_VERSION; print('VERSION', 'v'+$FOLDER_WITH_VERSION.__version__)" | grep VERSION | sed "s/VERSION //g")
        git tag $PACKAGE_VERSION
        git push origin $PACKAGE_VERSION